name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}  # CLOUDTYPE_TOKEN 생성 필요
          ghtoken: ${{ secrets.GHP_TOKEN }}  # GHP 토큰 생성 필요
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}  # CLOUDTYPE_TOKEN 생성 필요
          project: 본인_github_id/python-django
          stage: main
          yaml: |
            name: python-django
            app: python@3.9
            options:
              env:
                - name: DJANGO_SECRET
                  value: 5xeuu%71e@wu=#f@^xs6fp0d$adc@c7dvk@8-gfb%0r@ynpe*-
              ports: 8000
              start: python3 manage.py runserver 0:8000
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: python-django